ALTER TABLE episodios
ADD CONSTRAINT FK_ESTRELA
FOREIGN KEY (id_estrela_1) REFERENCES personagens(ID);

ALTER TABLE episodios
ADD CONSTRAINT FK_ESTRELA_1
FOREIGN KEY (id_estrela_2) REFERENCES personagens(ID);

ALTER TABLE episodios
ADD CONSTRAINT FK_ESTRELA_2
FOREIGN KEY (id_estrela_3) REFERENCES personagens(ID);